# Generated by Django 3.2.7 on 2021-10-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='portal_student',
        ),
    ]
