# Generated by Django 3.2.7 on 2021-10-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Model',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_usr_name', models.CharField(max_length=50)),
                ('admin_pwd', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'admin_tbl',
            },
        ),
        migrations.CreateModel(
            name='Students_Model',
            fields=[
                ('stdnt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stdnt_Name', models.CharField(max_length=50)),
                ('stdnt_Roll', models.CharField(max_length=50)),
                ('stdnt_Email', models.EmailField(max_length=254)),
                ('stdnt_Mobile', models.CharField(max_length=10)),
                ('stdnt_UserName', models.CharField(max_length=50)),
                ('stdnt_PWD', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'students_tbl',
            },
        ),
        migrations.CreateModel(
            name='Teachers_Model',
            fields=[
                ('tech_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teach_Name', models.CharField(max_length=50)),
                ('teach_Email', models.EmailField(max_length=254)),
                ('teach_Mobile', models.CharField(max_length=10)),
                ('teach_UserName', models.CharField(max_length=50)),
                ('teach_PWD', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'teachers_tbl',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
