# Generated by Django 4.0.5 on 2022-06-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_book_issue_model_book_issue_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue_model',
            name='book_issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
