# Generated by Django 4.0.5 on 2022-07-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_attendance_model_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_Model',
            fields=[
                ('parent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_Name', models.CharField(max_length=50)),
                ('parent_stdnt_Roll', models.CharField(max_length=50)),
                ('parebt_Email', models.EmailField(max_length=254)),
                ('parent_Mobile', models.CharField(max_length=10)),
                ('parent_PWD', models.CharField(max_length=250)),
                ('parent_is_Active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'parent_tbl',
            },
        ),
    ]
