# Generated by Django 3.2.7 on 2021-10-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20211018_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_model',
            name='stdnt_DOB',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
