# Generated by Django 4.0.5 on 2022-07-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_parent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_model',
            name='parent_stdnt_Roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.students_model'),
        ),
    ]
