# Generated by Django 3.2.7 on 2021-10-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_assignments_assignment_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment_Marks',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
