# Generated by Django 4.0.5 on 2022-07-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_parent_model_parent_stdnt_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_model',
            name='stdnt_Parent_id',
            field=models.ForeignKey(default='1',on_delete=django.db.models.deletion.CASCADE, to='portal.parent_model'),
            preserve_default=False,
        ),
    ]
