# Generated by Django 3.2.7 on 2021-10-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_assignments_assignment_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_Last_Date',
            field=models.CharField(max_length=50),
        ),
    ]
