# Generated by Django 3.2.7 on 2021-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_assignments_assignment_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment_FileType',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
