# Generated by Django 3.2.7 on 2021-10-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_assignments_assignment_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignemnt_submissions',
            name='assignment_Model_ID',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
