# Generated by Django 3.2.7 on 2021-10-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_assignemnt_submissions_assignment_submittion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignemnt_submissions',
            name='assignment_submitted_File',
            field=models.CharField(max_length=150),
        ),
    ]
