# Generated by Django 3.2.7 on 2021-10-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_assignemnt_submissions_assignment_submitted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignemnt_submissions',
            name='assignment_submited_Marks',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
