# Generated by Django 3.2.13 on 2022-06-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_assignemnt_submissions_assignment_submited_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees_Model',
            fields=[
                ('fees_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fees_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fees_tbl',
            },
        ),
        migrations.CreateModel(
            name='Payments_Model',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('fees_type_id', models.CharField(max_length=50)),
                ('fees_submited_Roll', models.CharField(max_length=50)),
                ('razorpay_payment_id', models.CharField(max_length=250)),
                ('payment_submittion_date', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'payments_tbl',
            },
        ),
        migrations.AddField(
            model_name='students_model',
            name='stdnt_Total_Fees',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
