# Generated by Django 3.2.13 on 2022-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20220612_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_model',
            name='payment_state',
            field=models.BooleanField(default=True),
        ),
    ]
