# Generated by Django 3.2.13 on 2022-06-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_payments_model_payment_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_usr',
            fields=[
                ('acc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acc_Name', models.CharField(max_length=50)),
                ('acc_Gender', models.BooleanField(default=False)),
                ('acc_Email', models.EmailField(max_length=254)),
                ('acc_Mobile', models.CharField(max_length=10)),
                ('acc_UserName', models.CharField(max_length=50)),
                ('acc_PWD', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'accounts_usr',
            },
        ),
    ]
