# Generated by Django 3.2.13 on 2022-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_accounts_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_model',
            name='fee_payment_mode',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
