# Generated by Django 3.2.13 on 2022-06-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_payments_model_fee_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_model',
            name='fees_type',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
