# Generated by Django 4.0.5 on 2022-06-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_fees_model_fees_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_model',
            name='fees_amount',
            field=models.IntegerField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
