# Generated by Django 4.0.5 on 2022-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_fees_model_fees_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments_model',
            old_name='fees_type_id',
            new_name='fees_type',
        ),
        migrations.RemoveField(
            model_name='payments_model',
            name='fee_payment_mode',
        ),
        migrations.AlterField(
            model_name='fees_model',
            name='fees_amount',
            field=models.IntegerField(),
        ),
    ]
