# Generated by Django 4.0.5 on 2022-06-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_rename_fees_type_id_payments_model_fees_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments_model',
            name='razorpay_payment_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
