# Generated by Django 4.0.5 on 2022-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_payments_model_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_model',
            name='reason',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
