# Generated by Django 4.0.5 on 2022-06-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_payments_model_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_model',
            name='amount',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
