# Generated by Django 4.0.5 on 2022-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_payments_model_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices_Model',
            fields=[
                ('notice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notice_added_user', models.CharField(max_length=50)),
                ('notice_issue_date', models.DateTimeField(auto_now_add=True)),
                ('notice_name', models.CharField(max_length=50)),
                ('notice_description', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'notice_tbl',
            },
        ),
    ]
