# Generated by Django 4.0.5 on 2022-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_notices_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notices',
        ),
        migrations.AlterField(
            model_name='assignemnt_submissions',
            name='assignment_submittion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payments_model',
            name='payment_submittion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
